[build]
  base = "."
  publish = "./dist/"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
  
[[redirects]]
  from = "https://shrq.netlify.app/*"
  to = "https://sharq.tech/:splat"
  status = 301